/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.disenosoft.universidad.logica.excepciones.ExcepcionNegocio;
import co.edu.eam.disenosoft.universidad.modelo.Asignatura;
import co.edu.eam.disenosoft.universidad.modelo.Curso;
import co.edu.eam.disenosoft.universidad.modelo.Evaluacion;
import co.edu.eam.disenosoft.universidad.modelo.Profesion;
import co.edu.eam.disenosoft.universidad.modelo.SesionCurso;
import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorCrearCalificacion;

/**
 *
 * @author dir_software
 */
public class VentanaCrearCalificacion extends javax.swing.JInternalFrame {

	/**
	 * Creates new form VentanaCrearCalificacion
	 */
	private ControladorCrearCalificacion controlador;

	public VentanaCrearCalificacion() {
		controlador = new ControladorCrearCalificacion();
		initComponents();
		setVisible(true);
		setMaximizable(false);
		setIconifiable(true);
		setResizable(false);
		setClosable(true);
		btnQuitarCalificacion.setEnabled(false);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfcodigoasignatura = new javax.swing.JTextField();
		btnBuscarAsignatura = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		tfnombreasignatura = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel4 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablaCalificaciones = new javax.swing.JTable();
		jLabel5 = new javax.swing.JLabel();
		tfnombrecal = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		tfnombrepor = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		tfporcentajenoasignado = new javax.swing.JTextField();
		jBAgregarCalificacion = new javax.swing.JButton();
		btnQuitarCalificacion = new javax.swing.JButton();

		setTitle("Administrar Calificaciones Curso");
		setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a10icono.png"))); // NOI18N

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

		jLabel1.setText("Codigo");

		btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
		btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarAsignaturaActionPerformed(evt);
			}
		});

		jLabel2.setText("Nombre");

		tfnombreasignatura.setEditable(false);

		jLabel3.setText("Curso");

		jComboBox1.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboBox1ItemStateChanged(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout
										.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1)
														.addGap(37, 37, 37).addComponent(tfcodigoasignatura,
																javax.swing.GroupLayout.PREFERRED_SIZE, 231,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel1Layout
														.createSequentialGroup()
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel2).addComponent(jLabel3))
														.addGap(33, 33, 33)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(tfnombreasignatura)
																.addComponent(jComboBox1, 0,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 88,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(5, 5, 5).addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1).addComponent(tfcodigoasignatura,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(tfnombreasignatura, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel2))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3).addComponent(jComboBox1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(29, Short.MAX_VALUE)));

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a10.png"))); // NOI18N

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Calificaciones Curso"));

		tablaCalificaciones.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null }, { null, null }, { null, null }, { null, null } },
				new String[] { "Nombre", "Porcentaje" }));
		jScrollPane1.setViewportView(tablaCalificaciones);

		jLabel5.setText("Nombre");

		jLabel6.setText("Porcentaje");

		tfnombrepor.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				tfnombreporKeyTyped(evt);
			}
		});

		jLabel7.setText("No Asignado");

		tfporcentajenoasignado.setEditable(false);
		tfporcentajenoasignado.setToolTipText("Porcentaje faltante por asignar");

		jBAgregarCalificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
		jBAgregarCalificacion.setToolTipText("Agregar Calificacion");
		jBAgregarCalificacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBAgregarCalificacionActionPerformed(evt);
			}
		});

		btnQuitarCalificacion
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication.png"))); // NOI18N
		btnQuitarCalificacion.setToolTipText("Quitar Calificacion Seleccionada");
		btnQuitarCalificacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQuitarCalificacionActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout
						.createSequentialGroup()
						.addContainerGap().addGroup(jPanel2Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout
										.createSequentialGroup()
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel5).addComponent(jLabel6)
												.addComponent(jLabel7))
										.addGap(21, 21, 21)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(tfporcentajenoasignado,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE, 247,
																Short.MAX_VALUE)
														.addComponent(tfnombrepor,
																javax.swing.GroupLayout.Alignment.LEADING))
												.addComponent(tfnombrecal, javax.swing.GroupLayout.PREFERRED_SIZE, 247,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jBAgregarCalificacion))
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnQuitarCalificacion))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(
						jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								jPanel2Layout
										.createSequentialGroup().addGap(26, 26, 26)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(tfnombrecal,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(jPanel2Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel6).addComponent(tfnombrepor,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(jPanel2Layout.createSequentialGroup()
														.addGap(1, 1, 1).addComponent(jBAgregarCalificacion,
																javax.swing.GroupLayout.DEFAULT_SIZE, 49,
																Short.MAX_VALUE)))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel7).addComponent(tfporcentajenoasignado,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(23, 23, 23)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(btnQuitarCalificacion).addContainerGap(20, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel2,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
								.addGap(34, 34, 34).addComponent(jLabel4).addGap(18, 18, 18).addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addGap(0, 18, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jComboBox1ItemStateChanged
		Curso curso = (Curso) jComboBox1.getSelectedItem();
		if (curso != null) {
			try {
				porcentajeNoAsignado(curso);
				cargarEvaluacionesCurso(curso);
			} catch (Exception e) {
				e.printStackTrace();
				JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Crear Calificacion",
						JOptionPane.ERROR_MESSAGE);
			}
		}
	}

	private void tfnombreporKeyTyped(java.awt.event.KeyEvent evt) {
		char c = evt.getKeyChar();
		if ((c < '0' || c > '9')) {
			evt.consume();
			JOptionPane.showMessageDialog(null, "Por favor, solo numeros", "Informacion",
					JOptionPane.INFORMATION_MESSAGE);
		}
	}

	private void jBAgregarCalificacionActionPerformed(java.awt.event.ActionEvent evt) {
		String nombreEvaluacion = tfnombrecal.getText();
		String cporcentaje = tfnombrepor.getText();
		String codigo = tfcodigoasignatura.getText();
		Curso curso = (Curso) jComboBox1.getSelectedItem();
		if (codigo.isEmpty() || curso == null) {
			JOptionPane.showMessageDialog(null, "por favor, busque la asignatura y seleccione un curso",
					"Administrador Crear Calificacion", JOptionPane.WARNING_MESSAGE);
		} else {
			if (nombreEvaluacion.isEmpty() || cporcentaje.isEmpty()) {
				JOptionPane.showMessageDialog(null, "por favor, ingrese el nombre y porcentaje de la evaluacion",
						"Administrador Crear Calificacion", JOptionPane.WARNING_MESSAGE);
			} else {
				if (isDouble(cporcentaje)) {
					double porcentaje = Double.parseDouble(cporcentaje);
					if (porcentaje > 100 || porcentaje < 0) {
						JOptionPane.showMessageDialog(null,
								"El porcentaje no puede superar el 100%\nNo debe ser valor negativo",
								"Administrador Crear Calificacion", JOptionPane.WARNING_MESSAGE);
					} else {
						try {
							Evaluacion evaluacion = new Evaluacion(nombreEvaluacion, porcentaje, curso);
							controlador.crearEvaluacion(evaluacion);
							JOptionPane.showMessageDialog(null, "Se ha registrado la Evaluacion ",
									"Administrador Crear Calificacion", JOptionPane.QUESTION_MESSAGE);
							limpiarCamposEvaluacion();
							porcentajeNoAsignado(curso);
							cargarEvaluacionesCurso(curso);
						} catch (ExcepcionNegocio ex) {
							JOptionPane.showMessageDialog(null, ex.getMessage(), "Administrador Crear Calificacion",
									JOptionPane.WARNING_MESSAGE);
						} catch (Exception e) {
							e.printStackTrace();
							JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.",
									"Administrador Crear Calificacion", JOptionPane.ERROR_MESSAGE);
						}
					}
				} else {
					JOptionPane.showMessageDialog(null, "El porcentaje debe ser numerico",
							"Administrador Crear Calificacion", JOptionPane.WARNING_MESSAGE);
				}
			}
		}
	}

	private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {
		String codigo = tfcodigoasignatura.getText();
		if (!codigo.isEmpty()) {
			try {
				Asignatura a = controlador.buscarAsignatura(codigo);
				if (a != null) {
					tfnombreasignatura.setText(a.getNombre());
					cargarCursosAsignatura(a);
				} else {
					limpiarCamposAsignatura();
					JOptionPane.showMessageDialog(null,
							"No se ha encontrado ninguna asignatura con el codigo " + codigo,
							"Administrador Crear Calificacion", JOptionPane.QUESTION_MESSAGE);
					limpiarCamposEvaluacion();
				}
			} catch (Exception e) {
				e.printStackTrace();
				JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Crear Calificacion",
						JOptionPane.ERROR_MESSAGE);
			}
		} else {
			JOptionPane.showMessageDialog(null, "por favor, ingrese el codigo de la asignatura a buscar",
					"Administrador Crear Calificacion", JOptionPane.WARNING_MESSAGE);
		}
	}

	private void btnQuitarCalificacionActionPerformed(java.awt.event.ActionEvent evt) {
		if (tablaCalificaciones.getSelectedRow() != -1) {
			try {
				Curso curso = (Curso) jComboBox1.getSelectedItem();
				int posicion = tablaCalificaciones.getSelectedRow();
				List<Evaluacion> evaluaciones = controlador.listarEvaluacionesCurso(curso);
				controlador.eliminarEvaluacion(evaluaciones.get(posicion));
				porcentajeNoAsignado(curso);
				cargarEvaluacionesCurso(curso);
				JOptionPane.showMessageDialog(null, "Se ha eliminado la evaluacion", "Administrador Crear Calificacion",
						JOptionPane.QUESTION_MESSAGE);
			} catch (ExcepcionNegocio ex) {
				JOptionPane.showMessageDialog(null, ex.getMessage(), "Administrador Crear Calificacion",
						JOptionPane.WARNING_MESSAGE);
			} catch (Exception e) {
				e.printStackTrace();
				JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Crear Calificacion",
						JOptionPane.ERROR_MESSAGE);
			}
		} else {
			JOptionPane.showMessageDialog(null, "por favor, seleccione la evaluacion que desea eliminar",
					"Administrador Crear Calificacion", JOptionPane.WARNING_MESSAGE);
		}
	}

	public void cargarCursosAsignatura(Asignatura a) {
		jComboBox1.removeAllItems();
		try {
			List<Curso> cursos = controlador.listaCursosByMateria(a);
			for (int i = 0; i < cursos.size(); i++) {
				jComboBox1.addItem(cursos.get(i));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void limpiarCamposAsignatura() {
		tfnombreasignatura.setText(null);
		cargarCursosAsignatura(null);
	}

	public void limpiarCamposEvaluacion() {
		tfnombrecal.setText(null);
		tfnombrepor.setText(null);
	}

	public void cargarEvaluacionesCurso(Curso curso) {
		try {
			DefaultTableModel table = (DefaultTableModel) tablaCalificaciones.getModel();
			table.setRowCount(0);
			List<Evaluacion> evaluaciones = controlador.listarEvaluacionesCurso(curso);
			if (evaluaciones.size() > 0) {
				for (Evaluacion evaluacion : evaluaciones) {
					table.addRow(new Object[] { evaluacion.getNombre(), evaluacion.getPorcentaje() + " %" });
				}
				btnQuitarCalificacion.setEnabled(true);
			} else {
				btnQuitarCalificacion.setEnabled(false);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public boolean isDouble(String cadena) {
		try {
			Double.parseDouble(cadena);
			return true;
		} catch (NumberFormatException nfe) {
			return false;
		}
	}

	public void porcentajeNoAsignado(Curso curso) {
		try {
			Double porcentanoNoAsignado = controlador.porcentajeNoAsignado(curso);
			tfporcentajenoasignado.setText(String.valueOf(porcentanoNoAsignado) + " %");
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBuscarAsignatura;
	private javax.swing.JButton btnQuitarCalificacion;
	private javax.swing.JButton jBAgregarCalificacion;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tablaCalificaciones;
	private javax.swing.JTextField tfcodigoasignatura;
	private javax.swing.JTextField tfnombreasignatura;
	private javax.swing.JTextField tfnombrecal;
	private javax.swing.JTextField tfnombrepor;
	private javax.swing.JTextField tfporcentajenoasignado;
	// End of variables declaration//GEN-END:variables
}
