package co.edu.eam.disenosoft.universidad.vista.gui;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JOptionPane;

import co.edu.eam.disenosoft.universidad.modelo.Docente;
import co.edu.eam.disenosoft.universidad.modelo.Estudiante;
import co.edu.eam.disenosoft.universidad.modelo.Persona;
import co.edu.eam.disenosoft.universidad.modelo.Profesion;
import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorAdminEstudiante;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.dao.definiciones.IDAOEstudiante;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.dao.implementacion.jdbc.DAOEstudianteJDBC;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.dao.implementacion.jpa.DAOEstudianteJPA;

public class VentanaAdminEstudiante extends javax.swing.JInternalFrame{
	/**
	 * Creates new form VentanaAdminEstudiante
	 */
//  private IDAOEstudiante dao;
	private ControladorAdminEstudiante controlador;
	public VentanaAdminEstudiante() {
		initComponents();
		setVisible(true);
		setMaximizable(false);
		setIconifiable(true);
		setClosable(true);
		setResizable(false);
//      dao = new DAOEstudianteJPA();
//      dao = new DAOEstudianteJDBC();
		controlador = new ControladorAdminEstudiante();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfCEdula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCorreo = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        brtnEditar = new javax.swing.JButton();
        brtnEliminar = new javax.swing.JButton();

        setMaximizable(true);
        setResizable(true);
        setTitle("Administrar Estudiantes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/student6.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

        jLabel6.setText("Telefono");

        jLabel2.setText("Nombre");

        jLabel1.setText("Cedula");

        jLabel5.setText("Direccion");

        jLabel4.setText("Correo Electronico");

        jLabel3.setText("Apellido");

        jLabel7.setText("Fecha Nacimiento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(25, 25, 25)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCEdula, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(tfNombre)
                    .addComponent(tfApellido)
                    .addComponent(tfCorreo)
                    .addComponent(tfDireccion)
                    .addComponent(tfTelefono)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCEdula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        brtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pen38.png"))); // NOI18N
        brtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brtnEditarActionPerformed(evt);
            }
        });

        brtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        brtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(brtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(brtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(brtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {
    	try{
    		String nombre = tfNombre.getText(); 
    		String apellido = tfApellido.getText(); 
    		String cedula = tfCEdula.getText(); 
    		String correo = tfCorreo.getText(); 
    		String direccion = tfDireccion.getText(); 
    		String telefono = tfTelefono.getText();
    		Date fechaNacimiento = jDateChooser1.getDate();
    		if(cedula.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || correo.isEmpty() || direccion.isEmpty() || telefono.isEmpty()){
    			JOptionPane.showMessageDialog(null, "Por favor, ingrese todos los datos.", "Administrador de Estudiantes", JOptionPane.INFORMATION_MESSAGE);   
    		}else{
    			Estudiante estudiante = new Estudiante(cedula, apellido, correo, direccion, nombre, telefono, fechaNacimiento);
    			System.out.println("Guardando los datos...");
//    			dao.crear(estudiante);
    			Persona p = controlador.buscarPersona(estudiante.getCedula());
    			if(p == null){
    				controlador.crear(estudiante);
        			JOptionPane.showMessageDialog(null, "Se ha registrado el estudiante.", "Administrador de Estudiantes", JOptionPane.INFORMATION_MESSAGE); 
        			limpiarCampos();
    			}else{
    				JOptionPane.showMessageDialog(null, "Ya hay un estudiante con el numero de cedula "+estudiante.getCedula(), "Administrador de Estudiantes", JOptionPane.WARNING_MESSAGE); 
    			}
    		}
    	}catch(Exception e1){
    		e1.printStackTrace();
    		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador de Estudiantes", JOptionPane.ERROR_MESSAGE);   
    	}
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {
    	try{
    		String cedula = tfCEdula.getText(); 
    		if(cedula.isEmpty()){
    			JOptionPane.showMessageDialog(null, "Por favor, ingrese el numero de cedula a buscar.", "Administrador de Estudiantado", JOptionPane.QUESTION_MESSAGE);   
    		}else{
    			Estudiante estudiante = controlador.buscar(cedula);
    			if(estudiante != null){
            		tfNombre.setText(estudiante.getNombre());
            		tfApellido.setText(estudiante.getApellido());
            		tfCEdula.setText(estudiante.getCedula());
            		tfCorreo.setText(estudiante.getCorreo());
            		tfDireccion.setText(estudiante.getDireccion());
            		tfTelefono.setText(estudiante.getTelefono());
            		jDateChooser1.setDate(estudiante.getFechaNacimiento());
    			}else{
        			JOptionPane.showMessageDialog(null, "No se ha encontrado ningun estudiante\ncon el numero de cedula "+cedula, "Administrador de Estudiantado", JOptionPane.INFORMATION_MESSAGE);   
    			}
    		}
    	}catch(Exception e1){
    		e1.printStackTrace();
    		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador de Estudiantado", JOptionPane.ERROR_MESSAGE);   
    	}
    }

    private void brtnEditarActionPerformed(java.awt.event.ActionEvent evt) {
    	try{
    		String nombre = tfNombre.getText(); 
    		String apellido = tfApellido.getText(); 
    		String cedula = tfCEdula.getText(); 
    		String correo = tfCorreo.getText(); 
    		String direccion = tfDireccion.getText(); 
    		String telefono = tfTelefono.getText(); 
    		Date fechaNacimiento = jDateChooser1.getDate();
    		if(cedula.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || correo.isEmpty() || direccion.isEmpty() || telefono.isEmpty()){
    			JOptionPane.showMessageDialog(null, "Por favor, ingrese todos los datos.", "Administrador de Estudiantado", JOptionPane.INFORMATION_MESSAGE);   
    		}else{
    			Estudiante estudiante = new Estudiante(cedula, apellido, correo, direccion, nombre, telefono, fechaNacimiento);
    			controlador.editar(estudiante);
    			JOptionPane.showMessageDialog(null, "Se ha Actualizado la informacion correctamente.", "Administrador de Estudiantado", JOptionPane.INFORMATION_MESSAGE);  
    			limpiarCampos();
    		}
    	}catch(Exception e1){
    		e1.printStackTrace();
    		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador de Estudiantado", JOptionPane.ERROR_MESSAGE);   
    	}
    }

    private void brtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {
      	try{
            String cedula = tfCEdula.getText(); 
            if(cedula.isEmpty()){
                JOptionPane.showMessageDialog(null, "Por favor, ingrese el numero de cedula.", "Administrador de Estudiantes", JOptionPane.QUESTION_MESSAGE);   
            }else{
            	controlador.eliminar(cedula);
                JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente", "Administrador de Estudiantes", JOptionPane.INFORMATION_MESSAGE);   
                limpiarCampos();
            }
      	}catch(Exception e1){
      		e1.printStackTrace();
      		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador de Estudiantes", JOptionPane.ERROR_MESSAGE);   
      	}
    }
    

    public void limpiarCampos(){
    	tfCEdula.setText(null);
    	tfApellido.setText(null);
    	tfCorreo.setText(null);
    	tfNombre.setText(null);
        tfDireccion.setText(null);
        tfTelefono.setText(null);
        jDateChooser1.setDate(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brtnEditar;
    private javax.swing.JButton brtnEliminar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCEdula;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables

}
