/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.disenosoft.universidad.modelo.Asignatura;
import co.edu.eam.disenosoft.universidad.modelo.Curso;
import co.edu.eam.disenosoft.universidad.modelo.Estudiante;
import co.edu.eam.disenosoft.universidad.modelo.Evaluacion;
import co.edu.eam.disenosoft.universidad.modelo.RegistroCurso;
import co.edu.eam.disenosoft.universidad.modelo.SesionCurso;
import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorVerCurso;

/**
 *
 * @author dir_software
 */
public class VentanaVerCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaVerCurso
     */
	private ControladorVerCurso controlador;
    public VentanaVerCurso() {
    	controlador = new ControladorVerCurso();
        initComponents();
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setResizable(false);
        setClosable(true);
        setClosable(true);
        btnVerEstudiante.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfcodigoasignatura = new javax.swing.JTextField();
        btnBuscarAsignatura = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfnombreasignatura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboCursos = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnVerEstudiante = new javax.swing.JButton();

        setTitle("Ver Curso");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/classroom.png"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Edad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

        jLabel1.setText("Codigo");

        btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
        btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsignaturaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        tfnombreasignatura.setEditable(false);

        jLabel3.setText("Curso");

        comboCursos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCursosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(tfcodigoasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnombreasignatura)
                            .addComponent(comboCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfcodigoasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfnombreasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/classroom.png"))); // NOI18N

        btnVerEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/student6.png"))); // NOI18N
        btnVerEstudiante.setToolTipText("Ver Estudiante");
        btnVerEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1))
                    .addComponent(btnVerEstudiante))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerEstudiante)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerEstudianteActionPerformed(java.awt.event.ActionEvent evt) {
    	if(jTable1.getSelectedRow() != -1){
    		
    		try {
				
	    		int pos = jTable1.getSelectedRow();
	    		Curso curso = (Curso) comboCursos.getSelectedItem();
	    		if(curso != null){
		    		List<RegistroCurso> registros = controlador.listaEstudiantesCurso(curso);
		    		DialogoVerEstudiante dialogo= new DialogoVerEstudiante(registros.get(pos));
	    		}else{
	          		JOptionPane.showMessageDialog(null, "Por favor, seleccione un curso", "Administrador Ver Curso", JOptionPane.WARNING_MESSAGE);   
	    		}
			} catch (Exception e) {
				e.printStackTrace();
			}
    	}else{
      		JOptionPane.showMessageDialog(null, "Por favor, seleccione un estudiante para ver su infromacion detallada", "Administrador Ver Curso", JOptionPane.WARNING_MESSAGE);   
    	}
        
    }

    private void comboCursosItemStateChanged(java.awt.event.ItemEvent evt) {
   	 Curso curso = (Curso) comboCursos.getSelectedItem();
   	 if(curso != null){
   		try {
   			cargarEstudiantesCurso(curso);
		} catch (Exception e) {
			e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Crear Calificacion", JOptionPane.ERROR_MESSAGE);   
		}
   	 }
    }

    private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        String codigo = tfcodigoasignatura.getText();
        if(codigo.isEmpty()){
      		JOptionPane.showMessageDialog(null, "por favor, ingrese el codigo de la asignatura a buscar", "Administrador Ver Curso", JOptionPane.WARNING_MESSAGE);   
        }else{
        	try{
            		Asignatura a = controlador.buscarAsignatura(codigo);
            		if(a != null){
            			tfnombreasignatura.setText(a.getNombre());
            			cargarCursosAsignatura(a);
            			btnVerEstudiante.setEnabled(true);
            		}else{
            			limpiarCamposAsignatura();
            			cargarEstudiantesCurso(null);
                		JOptionPane.showMessageDialog(null, "No se ha encontrado ninguna asignatura con el codigo "+codigo, "Administrador Ver Curso", JOptionPane.QUESTION_MESSAGE);  
            		}
            } catch(Exception e){
            	e.printStackTrace();
            	JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Ver Curso", JOptionPane.ERROR_MESSAGE);   
            }
        }
    }
    public void cargarCursosAsignatura(Asignatura a){
        /* Primero se limpia el combo para que los elementos no queden repetidos */
    	comboCursos.removeAllItems();
		try {
	    	List<Curso> cursos = controlador.listaCursosByMateria(a);
	        for(int i=0;i<cursos.size();i++){
	        	comboCursos.addItem(cursos.get(i));
	        } 
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
    public void limpiarCamposAsignatura(){
    	tfnombreasignatura.setText(null);
    	cargarCursosAsignatura(null);
    }
    public void cargarEstudiantesCurso(Curso curso){
    	try {
    		DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
    		table.setRowCount(0);
    		List<RegistroCurso> registros = controlador.listaEstudiantesCurso(curso);
    		if(registros.size() > 0){
				for (RegistroCurso rc : registros) {
					table.addRow(new Object[]{rc.getEstudiante().getCedula(),rc.getEstudiante().getNombre(),rc.getEstudiante().getApellido(),rc.getEstudiante().getFechaNacimiento()});
				}
    		}
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAsignatura;
    private javax.swing.JButton btnVerEstudiante;
    private javax.swing.JComboBox comboCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfcodigoasignatura;
    private javax.swing.JTextField tfnombreasignatura;
    // End of variables declaration//GEN-END:variables
}
