/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.disenosoft.universidad.logica.excepciones.ExcepcionNegocio;
import co.edu.eam.disenosoft.universidad.modelo.Asignatura;
import co.edu.eam.disenosoft.universidad.modelo.Curso;
import co.edu.eam.disenosoft.universidad.modelo.Estudiante;
import co.edu.eam.disenosoft.universidad.modelo.RegistroCurso;
import co.edu.eam.disenosoft.universidad.modelo.SesionCurso;
import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorRegistrarCurso;

/**
 *
 * @author dir_software
 */
public class VentanaRegistrarCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaRegistrarCurso
     */
	private ControladorRegistrarCurso controlador;
    public VentanaRegistrarCurso() {
    	controlador = new ControladorRegistrarCurso();
        initComponents();
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setResizable(false);
        setClosable(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfcodigoasignatura = new javax.swing.JTextField();
        btnBuscarAsignatura = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfnombreasignatura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHorario = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tfcreditosasignatura = new javax.swing.JTextField();
        btnRegistrarAsignaturea = new javax.swing.JButton();
        btnQuitarAsignatura = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfTipoAsignatura = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfcedulaestudiante = new javax.swing.JTextField();
        btnBuscarEstuainte = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfnombreestudiante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfcreditosregistradosestudiante = new javax.swing.JTextField();

        setIconifiable(true);
        setTitle("Registrar Curso");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abc1.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

        jLabel1.setText("Codigo");

        btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
        btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsignaturaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        tfnombreasignatura.setEditable(false);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cursos Asignatura"));

        tablaHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Horario"
            }
        ));
        jScrollPane1.setViewportView(tablaHorario);

        jLabel5.setText("Creditos");

        tfcreditosasignatura.setEditable(false);

        btnRegistrarAsignaturea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
        btnRegistrarAsignaturea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAsignatureaActionPerformed(evt);
            }
        });

        btnQuitarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication.png"))); // NOI18N
        btnQuitarAsignatura.setToolTipText("Quitar Asignatura Registrada");
        btnQuitarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarAsignaturaActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo:");

        tfTipoAsignatura.setEditable(false);
        tfTipoAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTipoAsignaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfcreditosasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfTipoAsignatura))
                                    .addComponent(tfnombreasignatura, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                    .addComponent(tfcodigoasignatura))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarAsignatura))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRegistrarAsignaturea)
                                .addGap(18, 18, 18)
                                .addComponent(btnQuitarAsignatura)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfcodigoasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfnombreasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfcreditosasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfTipoAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrarAsignaturea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuitarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Estudiante"));

        jLabel3.setText("Cedula");

        btnBuscarEstuainte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscarEstuainte.setToolTipText("Buscar Docente");
        btnBuscarEstuainte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstuainteActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        tfnombreestudiante.setEditable(false);

        jLabel6.setText("Creditos Registrados");

        tfcreditosregistradosestudiante.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfcedulaestudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(tfnombreestudiante)
                    .addComponent(tfcreditosregistradosestudiante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnBuscarEstuainte, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBuscarEstuainte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfcedulaestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfnombreestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfcreditosregistradosestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Registramos una asignatura
     */
    private void btnRegistrarAsignatureaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAsignatureaActionPerformed
        String cedula = tfcedulaestudiante.getText();
        String codigo = tfcodigoasignatura.getText();
    	if(codigo.isEmpty() || cedula.isEmpty()){
    		JOptionPane.showMessageDialog(null, "Por favor, busque el estudiante\nY la asignatura a registrar", "Administrador Registro Curso", JOptionPane.WARNING_MESSAGE);   
        }else{
        	try {
        		if(tablaHorario.getSelectedRow() != -1){
	                DefaultTableModel tm = (DefaultTableModel) tablaHorario.getModel(); 
	                String dato=String.valueOf(tm.getValueAt(tablaHorario.getSelectedRow(),0));
	                int codigoCurso = Integer.parseInt(dato);
					Estudiante e = controlador.buscarEstudiante(cedula);
					Curso c = controlador.buscarCurso(codigoCurso);
					if(c != null && e != null){
						RegistroCurso rc = new RegistroCurso(e, c);
						controlador.registrarCurso(rc);
			    		JOptionPane.showMessageDialog(null, "Se ha registrado en el curso correctamente", "Administrador Registro Curso", JOptionPane.QUESTION_MESSAGE);   
			    		int sumaCreditos = controlador.sumaCreditosByAlumno(e);
						tfcreditosregistradosestudiante.setText(String.valueOf(sumaCreditos));
					}else{
			    		JOptionPane.showMessageDialog(null, "No se ha encontrado el curso de la asignatura y/o el estudiante", "Administrador Registro Curso", JOptionPane.WARNING_MESSAGE);   
					}
        		}else{
		    		JOptionPane.showMessageDialog(null, "Por favor, seleccione un curso", "Administrador Registro Curso", JOptionPane.WARNING_MESSAGE);   
        		}
			}catch (ExcepcionNegocio ex) {
	    		JOptionPane.showMessageDialog(null, ex.getMessage(), "Administrador Registro Curso", JOptionPane.WARNING_MESSAGE);   
			}catch (Exception e) {
				e.printStackTrace();
	    		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Registro Curso", JOptionPane.ERROR_MESSAGE);   
			}
        	
        }
    }

    private void tfTipoAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTipoAsignaturaActionPerformed
    }
    /**
     * Buscamos un Estudiante
     */
    private void btnBuscarEstuainteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstuainteActionPerformed
    	String cedula = tfcedulaestudiante.getText();
    	if(!cedula.isEmpty()){
    		try {
				Estudiante estudiante = controlador.buscarEstudiante(cedula);
				if(estudiante != null){
					tfnombreestudiante.setText(estudiante.getNombre()+" "+estudiante.getApellido());
					int sumaCreditos = controlador.sumaCreditosByAlumno(estudiante);
					tfcreditosregistradosestudiante.setText(String.valueOf(sumaCreditos));
				}else{
		    		JOptionPane.showMessageDialog(null, "No se ha encontrado ningun estudiante\ncon el numero de cedula "+cedula, "Administrador Registro Curso", JOptionPane.WARNING_MESSAGE);   
				}
			} catch (Exception e) {
				e.printStackTrace();
	    		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Registro Curso", JOptionPane.ERROR_MESSAGE);   
			}
    	}else{
    		JOptionPane.showMessageDialog(null, "por favor, ingrese la cedula del estudiante a buscar", "Administrador Curso", JOptionPane.QUESTION_MESSAGE);  
    	}
    }
    /**
     * Buscamos la asignatura y mostramos sus datos
     */
    private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAsignaturaActionPerformed
    	String codigoAsignatura = tfcodigoasignatura.getText();
    	if(!codigoAsignatura.isEmpty()){
    		try {
				Asignatura asignatura = controlador.buscarAsignatura(codigoAsignatura);
				if(asignatura != null){
					tfnombreasignatura.setText(asignatura.getNombre());
					tfcreditosasignatura.setText(String.valueOf(asignatura.getNumeroCreditos()));
					tfTipoAsignatura.setText(asignatura.getTipo().name());
					llenarTablaRegistros(asignatura);
				}else{
					JOptionPane.showMessageDialog(null, "No se ha encontrado ninguna asignatura\ncon el codigo "+codigoAsignatura, "Administrador Registro Curso", JOptionPane.QUESTION_MESSAGE);   
				}
			} catch (Exception e) {
				e.printStackTrace();
	    		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Registro Curso", JOptionPane.ERROR_MESSAGE);   
			}
    	}else{
    		JOptionPane.showMessageDialog(null, "por favor, ingrese el codigo de la asignatura a buscar", "Administrador Registro Curso", JOptionPane.WARNING_MESSAGE);  
    	}    
    }
    /* Quitar Asignatura Registrada */
    private void btnQuitarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarAsignaturaActionPerformed
        String cedula = tfcedulaestudiante.getText();
        String codigo = tfcodigoasignatura.getText();
        if(cedula.isEmpty() || codigo.isEmpty()){
    		JOptionPane.showMessageDialog(null, "por favor, busque el Estudiante y/o la Asignatura", "Administrador Registro Curso", JOptionPane.WARNING_MESSAGE);  
        }else{
        	try {
				Estudiante e = controlador.buscarEstudiante(cedula);
				RegistroCurso rc = controlador.buscarRegistroCurso(e, codigo);
				if(rc != null){
					controlador.eliminarRegistroCurso(rc);
		    		JOptionPane.showMessageDialog(null, "Se ha Eliminado Correctamente de tu registro", "Administrador Registro Curso", JOptionPane.QUESTION_MESSAGE);  
		    		int sumaCreditos = controlador.sumaCreditosByAlumno(e);
					tfcreditosregistradosestudiante.setText(String.valueOf(sumaCreditos));
				}else{
		    		JOptionPane.showMessageDialog(null, "No se ha encontrado ningun Registro curso con esta Asignatura\nAl estudiante "+e.getNombre()+" "+e.getApellido(), "Administrador Registro Curso", JOptionPane.WARNING_MESSAGE);  
				}
			} catch (Exception e) {
	    		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Registro Curso", JOptionPane.ERROR_MESSAGE);   
				e.printStackTrace();
			}
        }
    }
    public void cargarCursosAsignatura(Asignatura asignatura){
    	try {
    		DefaultTableModel table = (DefaultTableModel) tablaHorario.getModel();
    		table.setRowCount(0);
    		List<Curso> cursos = controlador.listaCursosByMateria(asignatura);
    		if(cursos.size() > 0){
				for (Curso curso : cursos) {
					table.addRow(new Object[]{curso.getCodigo(),curso.getSesiones()});
				}
    		}
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
    public void llenarTablaRegistros(Asignatura asi){
    	try {
    	DefaultTableModel dtm = (DefaultTableModel) tablaHorario.getModel();
    	dtm.setRowCount(0);
    	
    	
    		List<Curso> cursos = controlador.listaCursosByMateria(asi);
			for (Curso curso : cursos) {
				
				String sesiones = ""; 
				
						
				for(int i=0;i<curso.getSesiones().size();i++){
				
					sesiones+= curso.getSesiones().get(i).getDia() +" ";
					sesiones+= curso.getSesiones().get(i).getHoraInicio() +"-";
					sesiones+= curso.getSesiones().get(i).getHoraFinal() +". ";

				}
				
			dtm.addRow(new Object[]{curso.getCodigo(),sesiones});
				
			}
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
    
    
    private javax.swing.JButton btnBuscarAsignatura;
    private javax.swing.JButton btnBuscarEstuainte;
    private javax.swing.JButton btnQuitarAsignatura;
    private javax.swing.JButton btnRegistrarAsignaturea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHorario;
    private javax.swing.JTextField tfTipoAsignatura;
    private javax.swing.JTextField tfcedulaestudiante;
    private javax.swing.JTextField tfcodigoasignatura;
    private javax.swing.JTextField tfcreditosasignatura;
    private javax.swing.JTextField tfcreditosregistradosestudiante;
    private javax.swing.JTextField tfnombreasignatura;
    private javax.swing.JTextField tfnombreestudiante;
    // End of variables declaration//GEN-END:variables
}
