/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.awt.event.ItemEvent;
import java.io.IOException;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.disenosoft.universidad.logica.excepciones.ExcepcionNegocio;
import co.edu.eam.disenosoft.universidad.modelo.Asignatura;
import co.edu.eam.disenosoft.universidad.modelo.Curso;
import co.edu.eam.disenosoft.universidad.modelo.Docente;
import co.edu.eam.disenosoft.universidad.modelo.Profesion;
import co.edu.eam.disenosoft.universidad.modelo.SesionCurso;
import co.edu.eam.disenosoft.universidad.modelo.enumeraciones.DiaEnum;
import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorAsignatura;
import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorCrearCurso;
import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorProfesor;
import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorVerCurso;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Carlos Martinez
 */
public class VentanaCrearCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaCrearCurso
     */
	private ControladorCrearCurso controlador;
	private ControladorAsignatura conAsig;
	private ControladorProfesor conDocente;
	private ControladorVerCurso conVerCurso;
   
	public VentanaCrearCurso() {
    	initComponents() ;
    	controlador = new ControladorCrearCurso();
    	conAsig = new ControladorAsignatura();
    	conDocente = new ControladorProfesor();
    	conVerCurso = new ControladorVerCurso();
    	setClosable(true);
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setResizable(false);
        cargarComboCursos();
        comboDia.addItem(DiaEnum.LUNES);
        comboDia.addItem(DiaEnum.MARTES);
        comboDia.addItem(DiaEnum.MIERCOLES);
        comboDia.addItem(DiaEnum.JUEVES);
        comboDia.addItem(DiaEnum.VIERNES);
        comboDia.addItem(DiaEnum.SABADO);
        comboDia.addItem(DiaEnum.DOMINGO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfcodigoasignatura = new javax.swing.JTextField();
        btnBuscarAsignatura = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfnombreasignatura = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfceduladocente = new javax.swing.JTextField();
        btnBuscarDocente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfnombredocente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboDia = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        comboHoraInicio = new javax.swing.JComboBox();
        comboHoraFin = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHorario = new javax.swing.JTable();
        btnAgregarSesion = new javax.swing.JButton();
        jBEliminarSesion = new javax.swing.JButton();
        comboCursos = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        brtnEditar = new javax.swing.JButton();

        setTitle("Administrar Curso");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/class.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

        jLabel1.setText("Codigo");

        btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
        btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnBuscarAsignaturaActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jLabel2.setText("Nombre");

        tfnombreasignatura.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfcodigoasignatura)
                    .addComponent(tfnombreasignatura))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfcodigoasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfnombreasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Docente"));

        jLabel3.setText("Cedula");

        btnBuscarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscarDocente.setToolTipText("Buscar Docente");
        btnBuscarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDocenteActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        tfnombredocente.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfceduladocente)
                    .addComponent(tfnombredocente))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfceduladocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfnombredocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Horario Asignatura"));

        jLabel5.setText("Dia");

        jLabel6.setText("Hora Inicio:");

        comboHoraInicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        comboHoraInicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboHoraInicioItemStateChanged(evt);
            }
        });

        comboHoraFin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        jLabel7.setText("Hora Fin:");

        tablaHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Dia", "Hora Inicial", "Hora Final"
            }
        ));
        jScrollPane1.setViewportView(tablaHorario);

        btnAgregarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
        btnAgregarSesion.setToolTipText("Agregar sesion");
        btnAgregarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSesionActionPerformed(evt);
            }
        });

        jBEliminarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation.png"))); // NOI18N
        jBEliminarSesion.setToolTipText("Quitar Sesion");
        jBEliminarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarSesionActionPerformed(evt);
            }
        });

        comboCursos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCursosItemStateChanged(evt);
            }
        });

        jLabel8.setText("Curso");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminarSesion)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(45, 45, 45)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(comboHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboDia, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(comboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(comboHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(comboHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnAgregarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBEliminarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
        btnCrear.setToolTipText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnCrearActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        brtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pen38.png"))); // NOI18N
        brtnEditar.setToolTipText("Editar");
        brtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brtnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(brtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) throws Exception {                                                    
        String codigoAsignatura = tfcodigoasignatura.getText();
        try{
	        Asignatura asignatura = conAsig.buscar(codigoAsignatura);
	        if(asignatura != null){
	        	tfnombreasignatura.setText(asignatura.getNombre());
	        }else{
	    		JOptionPane.showMessageDialog(null, "No se ha encontrado ninguna asignatura con el codigo "+codigoAsignatura, "Administrador Curso", JOptionPane.QUESTION_MESSAGE); 
	    		limpiarCamposAsignatura();
	        }
    	}catch(Exception e){
    		e.printStackTrace();
    		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Curso", JOptionPane.ERROR_MESSAGE);   
    	}
    }
    private void btnBuscarDocenteActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        String cedulaDocente = tfceduladocente.getText();
        try{
	        Docente docente = conDocente.buscar(cedulaDocente);
	        if(docente != null){
	        	tfnombredocente.setText(docente.getNombre());
	        }else{
	    		JOptionPane.showMessageDialog(null, "No se ha encontrado ninguna docente con la cedula "+cedulaDocente, "Administrador Curso", JOptionPane.QUESTION_MESSAGE);  
	    		limpiarCamposDocente();
	        }
    	}catch (ExcepcionNegocio ex){
    		JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);   
    	}
        catch(Exception e){
    		e.printStackTrace();
    		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Curso", JOptionPane.ERROR_MESSAGE);   
    	}
    }
    private void btnAgregarSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        if(comboCursos.getSelectedIndex() != 0){
	    	Curso curso = (Curso) comboCursos.getSelectedItem();
	        DiaEnum dia = (DiaEnum) comboDia.getSelectedItem();
	        int horaFinal = Integer.parseInt((String) comboHoraFin.getSelectedItem());
	        int horaInicio = Integer.parseInt((String) comboHoraInicio.getSelectedItem());
	        SesionCurso sesion = new SesionCurso(0, dia, horaFinal, horaInicio, curso);
	        try {
				if(Integer.parseInt((String) comboHoraFin.getSelectedItem())< Integer.parseInt((String) comboHoraInicio.getSelectedItem())){
		    		JOptionPane.showMessageDialog(null, "La hora final debe ser mayor a la hora inicial", "Administrador Curso", JOptionPane.ERROR_MESSAGE);  
				}else{
	        	controlador.crearSesion(sesion);
	    		JOptionPane.showMessageDialog(null, "Se ha Creado la Sesion", "Administrador Curso", JOptionPane.QUESTION_MESSAGE);  
	    		cargarSesiones(curso);
	    		resetSesion();
				
				}
	        }catch (ExcepcionNegocio ex){
	    		JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);   
	    	} catch (Exception e) {
				e.printStackTrace();
	    		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Curso", JOptionPane.ERROR_MESSAGE);   
			}
        }else{
    		JOptionPane.showMessageDialog(null, "Por favor, seleccione el curso", "Administrador Curso", JOptionPane.ERROR_MESSAGE);   
        }
    }
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnCrearActionPerformed
        String codigoAsignatura = tfcodigoasignatura.getText();
        String cedulaDocente = tfceduladocente.getText();
        try{
	        if(codigoAsignatura.isEmpty() || cedulaDocente.isEmpty()){
	    		JOptionPane.showMessageDialog(null, "Por favor, Busque la Asignatura y el docente\npara poder crear el curso", "Administrador Curso", JOptionPane.QUESTION_MESSAGE);  
	        }else{
	        	Docente docente= conDocente.buscar(cedulaDocente);
	            Asignatura asignatura = conAsig.buscar(codigoAsignatura);
	            if(docente != null && asignatura != null){
	            	Curso curso = new Curso(0, docente, asignatura);
	            	controlador.crearCurso(curso);
	        		JOptionPane.showMessageDialog(null, "Se ha Creado el curso", "Administrador Curso", JOptionPane.QUESTION_MESSAGE);  
	        		cargarComboCursos();
	        		limpiarCamposAsignatura();
	        		limpiarCamposDocente();
	            }else{
	        		JOptionPane.showMessageDialog(null, "El docente y/o asignatura no existen", "Administrador Curso", JOptionPane.QUESTION_MESSAGE);  
	            }
	        }
    	}catch (ExcepcionNegocio ex){
    		JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);   
    	}catch(Exception e){
    		e.printStackTrace();
    		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Curso", JOptionPane.ERROR_MESSAGE);   
    	}
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            int id = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el codigo del curso a Buscar", "Administrador Curso", JOptionPane.INFORMATION_MESSAGE));
			Curso curso = controlador.buscarCurso(id);
			if(curso != null){
				comboCursos.setSelectedItem(curso);
			}else{
	    		JOptionPane.showMessageDialog(null, "No se ha encontrado un curso con el codigo "+id, "Administrador Curso", JOptionPane.ERROR_MESSAGE);   
			}
	        comboCursos.setSelectedItem(id);
		} catch (ExcepcionNegocio ex){
    		JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);   
    	}catch (Exception e) {
			e.printStackTrace();
    		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Curso", JOptionPane.ERROR_MESSAGE);   
		}        
    }

    private void brtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brtnEditarActionPerformed
    	if(comboCursos.getSelectedIndex() != 0){
    		try {
				Asignatura asignatura = conAsig.buscar(tfcodigoasignatura.getText());
	    		Docente docente = conDocente.buscar(tfceduladocente.getText());
	    		if(asignatura != null && docente != null){
	    			Curso curso = (Curso) comboCursos.getSelectedItem();
	    			curso.setAsignatura(asignatura);
	    			curso.setDocente(docente);
	    			controlador.editarCurso(curso);
	        		JOptionPane.showMessageDialog(null, "Se ha editado el curso", "Administrador Curso", JOptionPane.QUESTION_MESSAGE);   
	    		}else{
	        		JOptionPane.showMessageDialog(null, "No se ha encontrado la asignatura o el docente", "Administrador Curso", JOptionPane.QUESTION_MESSAGE);   
	    		}
			} catch (ExcepcionNegocio ex){
	    		JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);   
	    	}catch (Exception e) {
	    		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Curso", JOptionPane.ERROR_MESSAGE);   
				e.printStackTrace();
			}
    	}else{
    		JOptionPane.showMessageDialog(null, "Por favor, primero busque o seleccione un Curso", "Administrador Curso", JOptionPane.ERROR_MESSAGE);   
    	}
    }

    private void jBEliminarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarSesionActionPerformed
        if(comboCursos.getSelectedIndex() != 0 && tablaHorario.getSelectedRow() != -1){
			try {
	        	Curso curso = (Curso) comboCursos.getSelectedItem();
				int sesion = tablaHorario.getSelectedRow();
				List<SesionCurso> sesiones = controlador.listarSesionesCurso(curso);
				controlador.eliminarSesion(sesiones.get(sesion).getId());
				cargarSesiones(curso);
			} catch (ExcepcionNegocio ex){
	    		JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);   
	    	}catch (Exception e) {
	    		JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador Curso", JOptionPane.ERROR_MESSAGE);   
				e.printStackTrace();
			}
        }else{
    		JOptionPane.showMessageDialog(null, "Seleccione la sesion ha eliminar", "Administrador Curso", JOptionPane.ERROR_MESSAGE);   
        }
    }

    private void comboHoraInicioItemStateChanged(java.awt.event.ItemEvent evt) {                                                 
    }

    private void comboCursosItemStateChanged(java.awt.event.ItemEvent evt) {                                             
		if(comboCursos.getSelectedIndex() != 0 && evt.getStateChange() == ItemEvent.SELECTED){
			try {
				Curso curso = (Curso) comboCursos.getSelectedItem();
				Asignatura asignatura = conAsig.buscar(curso.getAsignatura().getCodigo());
				if(asignatura != null){
					tfcodigoasignatura.setText(asignatura.getCodigo());
					tfnombreasignatura.setText(asignatura.getNombre());
				}else{
		    		JOptionPane.showMessageDialog(null, "Este curso no tiene Asignado una Asignatura", "Administrador Curso", JOptionPane.ERROR_MESSAGE);   
				}
				Docente docente = conDocente.buscar(curso.getDocente().getCedula());
				if(docente != null){
					tfceduladocente.setText(docente.getCedula());
					tfnombredocente.setText(docente.getNombre());
				}else{
		    		JOptionPane.showMessageDialog(null, "Este curso no tiene Asignado un Docente", "Administrador Curso", JOptionPane.ERROR_MESSAGE);   
				}
				cargarSesiones(curso);
			} catch (ExcepcionNegocio ex){
	    		JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);   
	    	}catch (Exception e) {
				e.printStackTrace();
			}
		}
    }

    public void limpiarCamposDocente(){
        tfceduladocente.setText(null);
        tfnombredocente.setText(null);
    }
    public void limpiarCamposAsignatura(){
        tfcodigoasignatura.setText(null);
        tfnombreasignatura.setText(null);
    }
    public void cargarComboCursos(){
		try {
	    	comboCursos.removeAllItems();
	    	comboCursos.addItem("Nuevo Curso o seleccione");
	    	List<Curso> lista;
			lista = controlador.listarCursos();
	        for(int i=0;i<lista.size();i++){
	        	comboCursos.addItem(lista.get(i));
	        }
		} catch (Exception e) {
			e.printStackTrace();
		} 
    }
    public void resetSesion(){
    	comboDia.setSelectedIndex(0);
    	comboHoraFin.setSelectedIndex(0);
    	comboHoraInicio.setSelectedIndex(0);
    }
    public void cargarSesiones(Curso curso){
    	try {
    		DefaultTableModel table = (DefaultTableModel) tablaHorario.getModel();
    		table.setRowCount(0);
    		List<SesionCurso> sesiones = controlador.listarSesionesCurso(curso);
    		if(sesiones.size() > 0){
				for (SesionCurso sesionCurso : sesiones) {
					table.addRow(new Object[]{sesionCurso.getDia(),sesionCurso.getHoraInicio(),sesionCurso.getHoraFinal()});
				}
    		}
		} catch (Exception e) {
			e.printStackTrace();
		}
    	
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brtnEditar;
    private javax.swing.JButton btnAgregarSesion;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarAsignatura;
    private javax.swing.JButton btnBuscarDocente;
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox comboCursos;
    private javax.swing.JComboBox comboDia;
    private javax.swing.JComboBox comboHoraFin;
    private javax.swing.JComboBox comboHoraInicio;
    private javax.swing.JButton jBEliminarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHorario;
    private javax.swing.JTextField tfceduladocente;
    private javax.swing.JTextField tfcodigoasignatura;
    private javax.swing.JTextField tfnombreasignatura;
    private javax.swing.JTextField tfnombredocente;
    // End of variables declaration//GEN-END:variables
}
